### ISSUE TITLE
More space on the left of the text

### ISSUE THREAD

**Issue by stefan-reich** [bobbylight/RSTAUI#10]
I think other editors have this - a little more margin on the left (beside the "s" of static):

![Screenshot](http://eyeocr.sourceforge.net/filestore/filestore.php?cmd=serve&file=blob_1004662&contentType=image/png)

Is it possible?

**Comment by bobbylight** [comment]
I'm closing this, but reopening it in the [RSyntaxTextArea issue tracker as #202](https://github.com/bobbylight/RSyntaxTextArea/issues/202), as that's a better place for it.
