### ISSUE TITLE
xPath search

### ISSUE THREAD

**Issue by JamzTheMan** [bobbylight/RSTAUI#11]
I love the find/replace toolbar! It saved me a lot of time having using it in my app!

I have an enhancement request, like the regex checkbox and searching, would it be difficult to put in a similar checkbox and function to evaluate xPath on a given XML document?

**Comment by bobbylight** [comment]
I probably won't be working on this since it's limited in scope (though admittedly useful if you're working on XML!) but pull requests are welcome.

**Comment by bobbylight** [comment]
Closing as won't fix, too specialized for this library.
