### ISSUE TITLE
Problems with find/replace dialogs

### ISSUE THREAD

**Issue by brunchboy** [bobbylight/RSTAUI#16]
I have been using RSyntaxtTextArea for a while to give people the ability to edit snippets of Clojure in [Beat Link Trigger](https://github.com/Deep-Symmetry/beat-link-trigger#beat-link-trigger), and now that my users are getting more ambitious in that regard, I am adopting RSTAUI as part of improving the editing experience. It’s going to be a great improvement of what is already a great editor!

I did run into what seem to be some small bugs in the Find and Replace dialogs, however, so I think I am going to omit those menu options for now, and just offer people the toolbars, which do seem to work fully, and are more compact anyway. But it might be nice to offer both options if you can fix these:

* The `Direction` radio buttons in both dialogs don’t work. If I click `Up`, then it is selected, but when I hit the `Find` button it still searches in a downwards direction (and immediately switches back to having `Down` selected).

* The `Replace All` button in the Replace dialog doesn’t work: adding logging to my `SearchListener` shows that it sends an ordinary `REPLACE` event instead of `REPLACE_ALL`.

Hopefully these might be easy fixes? But in any case, thanks so much for this wonderful set of libraries!

**Comment by bobbylight** [comment]
Wow, unbelievably broken!  Thanks for reporting.  This must worked and broken from some other change at some point, let me look into it.

**Comment by bobbylight** [comment]
This is fixed in the latest 3.0.3-SNAPSHOT you can grab from Sonatype here:

https://oss.sonatype.org/content/repositories/snapshots/com/fifesoft/rstaui/3.0.3-SNAPSHOT/

It'll also be in the 3.0.3 release build, which I should release to Maven Central in the next day or so.

**Comment by brunchboy** [comment]
Cool, thanks, I’ll give them a try and probably add menu options to let people use them.

**Comment by brunchboy** [comment]
When I try upgrading to release 3.0.3,  I can no longer instantiate `FindDialog`. Here is the relevant section of stack trace. Should I open this as a separate issue?

```
                                 beat-link-trigger.editors/build-search-tools                             editors.clj: 1070
                                                                          ...                                              
           jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance  DelegatingConstructorAccessorImpl.java:   45
               jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance      NativeConstructorAccessorImpl.java:   62
              jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0       NativeConstructorAccessorImpl.java     
                                    org.fife.rsta.ui.search.FindDialog.<init>                         FindDialog.java:   94
                     org.fife.rsta.ui.search.AbstractFindReplaceDialog.<init>          AbstractFindReplaceDialog.java:   91
                          org.fife.rsta.ui.search.AbstractSearchDialog.<init>               AbstractSearchDialog.java:  101
                            org.fife.rsta.ui.search.AbstractSearchDialog.init               AbstractSearchDialog.java:  404
                                              java.lang.ClassLoader.loadClass                        ClassLoader.java:  521
                    jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass                       ClassLoaders.java:  178
                             jdk.internal.loader.BuiltinClassLoader.loadClass                 BuiltinClassLoader.java:  581
java.lang.ClassNotFoundException: org.fife.ui.autocomplete.CompletionProvider
```

**Comment by brunchboy** [comment]
At a glance, it looks to me like it has a new dependency on another library, but I couldn’t see a change log file or anything that explained what I needed to do in order to successfully migrate to this new version.

**Comment by brunchboy** [comment]
I haven’t yet learned gradle, but I imagine it must have a facility similar to Maven where a project’s own dependencies can be recorded so they get pulled in automatically when another project uses this one?

**Comment by brunchboy** [comment]
I looked in the POM for this project on Maven Central, and it does not mention a dependency on AutoComplete. Since it is trying to load a class from it, it seems that is the most likely problem. If I had clue one about Gradle I’d submit a pull request to add it, but I don’t so that seems unwise. 😄

**Comment by brunchboy** [comment]
Reading over your README for RSTAUI, it looks like the project also needs a dependency on RSyntaxtTextArea in its Gradle configuration. That would eliminate the need to check out and compile either of those projects that you outline in the _Compiling_ section, and make sure the project works when used from Maven Central even if neither of those other components are referenced directly. (Although you could argue that the chances are virtually nil that anyone would use RSTAUI without RSyntaxtTextArea, it would still be the correct dependency declaration for this project.)

**Comment by brunchboy** [comment]
OK… I have been wanting to start learning some Gradle, and this gave me an excuse and a nice small way to start doing so. I’ve submitted a pair of pull requests that fix this problem (to this project and to RSyntaxTextArea).
