### ISSUE TITLE
Does not export its Maven dependencies

### ISSUE THREAD

**Issue by brunchboy** [bobbylight/RSTAUI#18]
Trying to use this in another project that is not itself using AutoComplete results in a crash due to a class not being found, because the project's `pom.xml` does not report its dependencies, as discussed in #16.

**Comment by bobbylight** [comment]
Should be wrapped up now, sorry for hte delay.  Let me know if you have any other issues!

**Comment by brunchboy** [comment]
Thanks for doing this! And there’s never a need to apologize for the schedule with which you can work on your free, open-source projects. I’m in the same boat after all. 😄
