### ISSUE TITLE
Forward and backward traversal through results using F3 and Shift-F3

### ISSUE THREAD

**Issue by proteusGIT** [bobbylight/RSTAUI#25]
Hi, Is there a way to enable forward and backward traversal through results using F3 and Shift-F3?

**Comment by bobbylight** [comment]
Not currently, without editing the key bindings yourself (of either the RSTA instance or of the Find/Replace dialogs in this library).

However, RSTA already essentially has this feature, just not tied to find/replace. Instead, it's tied to just selecting text.

* Select some text
* Ctrl+K (Cmd+K on macOS) finds the next instance of the selected text
* Ctrl/Cmd+Shift+K finds the previous instance

See [here](https://github.com/bobbylight/RSyntaxTextArea/wiki/Keyboard-Shortcut-List) for a more thorough (but not complete) keyboard shortcut list.

You can modify the `InputMap` to use F3 and Shift+F3 instead if you want. [Here's where](https://github.com/bobbylight/RSyntaxTextArea/blob/3b78fa5ad59dcfec5eb0cfc2f3943860b8b999fc/RSyntaxTextArea/src/main/java/org/fife/ui/rtextarea/RTADefaultInputMap.java#L128C1-L129) these key bindings are defined by default.
