### ISSUE TITLE
Replace in selection

### ISSUE THREAD

**Issue by proteusGIT** [bobbylight/RSTAUI#26]
Hi, is it possible to restrict find and replace to the current selection?

**Comment by bobbylight** [comment]
Not yet. The change would actually be in `RSyntaxTextArea`'s [SearchContext class](https://github.com/bobbylight/RSyntaxTextArea/blob/3b78fa5ad59dcfec5eb0cfc2f3943860b8b999fc/RSyntaxTextArea/src/main/java/org/fife/ui/rtextarea/SearchContext.java#L48). Please create a feature request there if you would find that feature useful.
