### ISSUE TITLE
Focus is not set correctly FIRST time when using the collapsible FindToolbar

### ISSUE THREAD

**Issue by eitzenbe** [bobbylight/RSTAUI#8]
Subject say sit all. I am able to reproduce this on Windows and Linux. But only the FIRST time you enter Ctrl+F (set as keystroke). Can you reproduce this or shall I try and minimize my code to have a test scenario?

br
Thomas

**Comment by bobbylight** [comment]
Not reproducible, though this ticket is admittedly very old so maybe it got fixed in the interim.
