### ISSUE TITLE
Wrap-around for search

### ISSUE THREAD

**Issue by stefan-reich** [bobbylight/RSTAUI#9]
Hi! I love this whole project, and I'm using it as the default editor in [my OS](http://botcompany.de)!

Here's something I'd really want: A wrap-around for the search dialog (search above AND below caret). Not having that is just a pain.

Cheers :-)

**Comment by stefan-reich** [comment]
Well... seems no one is working on this (sigh)

**Comment by siggemannen** [comment]
You can easily do wrapped search yourself by adapting the example code:

> 
>       case FIND:
>                 result = SearchEngine.find(textArea, context);
>                 
>                 if (!result.wasFound())
>                 {
>                     //Try to wrap the result...
>                     Caret c = textArea.getCaret();
>                     int pos = c.getDot();
>                     if (context.getSearchForward())
>                     {
>                         c.setDot(0);
>                     }
>                     else
>                     {
>                         c.setDot(textArea.getDocument().getLength());
>                     }
>                     result = SearchEngine.find(textArea, context);
>                     if (!result.wasFound())
>                     {
>                         c.setDot(pos);
>                         UIManager.getLookAndFeel().provideErrorFeedback(textArea);
>                     }
>                 }
>                 break;

**Comment by stefan-reich** [comment]
Thanks!! It works :-))
